### ISSUE TITLE
Question: Not showing all sensors and entities..

### ISSUE THREAD

**Issue by kababoom** [PimDoos/onesmartcontrolha#43] opened 2022-12-29 21:33 UTC
First of all, again thank you for this integration .....

After successful configuration and login we only see the 13 One Connect power sensors. 

How can we get the device sensors and control entities like SUN2000 and CO2? They are available in the App.

**Comment by PimDoos** [comment] 2022-12-30 15:52
I think this is caused by a bug which causes devices that are not assigned to a room to fail discovery. Should be fixed in v0.3.3.

**Closed** 2022-12-30 15:52 UTC
Labels: bug

**Comment by PimDoos** [comment] 2022-12-30 15:53
[v0.3.3 released](https://github.com/PimDoos/onesmartcontrolha/releases/tag/v0.3.3)

**Comment by kababoom** [comment] 2022-12-30 16:02
Going to try tonight, thank you ...
